### ISSUE TITLE
Suggestion: Making this work for footnotes

### ISSUE THREAD

**Issue by ajankit** [davidrthorn/cross_reference#12]
It would be amazing if you could get this to work for footnotes. The way you could do that is by not changing the text that the label is attached to when the document is updated, and _only_ changing the reference text. It would also work better if you allowed footnotes to be made into labels, as that is not currently allowed. Does Google Docs allow you to do this? If you can add this feature, I can tell you for sure that you will get a ton of new lawyer users.

**Comment by ajankit** [comment]
I thought about it a bit more and realized my specific suggestion on how to implement this wouldn't work at all. But if you could get this to work for footnotes through some method, that would be amazing

**Comment by davidrthorn** [comment]
Hi Ajankit, thanks for the suggestion

Just to be clear, do you mean you want to be able to refer to a footnote in the text, as in...

>See footnote 7 for more details.

...and have that update when footnote numbers change?

**Comment by ajankit** [comment]
Hey David,

Sorry for the late response. Being able to refer to footnotes in the text
as you describe would be great too. But what I am referring to is having
the ability to update the footnote references in the footnotes themselves.
So if footnote 20 said "see Jain, *supra *footnote 7", the footnote could
update as you add more footnotes to the document.

-Ankit

**Comment by davidrthorn** [comment]
This sounds similar to what I'm describing, except that it also allows you to add references to footnotes in other footnotes.

I just added the ability to label footnotes and am waiting Google review. This will allow you to refer to footnotes both in the main text and in other footnotes. So footnote 7 could say 'see footnote 8' for example.

Perhaps I'm still not getting it (not sure what *supra means), but hopefully the new feature captures what you have in mind. It shouldn't be too long!

**Comment by ajankit** [comment]
Yup you're right it's basically the same thing. "Supra" is a way to cite to
a previous footnote in legal documents--it was unnecessarily confusing to
include in the example so sorry about that haha. We will still have to make
every footnote into a label for it to work properly under your system,
right? Is there a way you could automate that so all footnotes
automatically become labels? Additionally, when we update the document,
will the labeled text still change as well? If that's the case then I don't
think it would be useful for lawyers, because the footnotes in the text of
the document need to stay the same. We only need the references to that
footnote to change. Thanks for taking my suggestions into account!

-Ankit

**Comment by ajankit** [comment]
Oh one other thing I noticed--you currently only allow one label per
paragraph. This would be a huge problem for lawyers trying to use your
extension because we will have multiple footnotes per paragraph (and
possibly per line as well) that we will want to be able to cross-reference.

-Ankit

**Comment by davidrthorn** [comment]
This is now in place. Raise further issues separarely if necessary.
