### ISSUE TITLE
Avoid Figure and label from being split by a page break

### ISSUE THREAD

**Issue by johngallo** [davidrthorn/cross_reference#17]
First off, Great work!  I'm so glad you've made this tool! Thank you.

Second, unless I am missing something, the figure and caption can be split by a page break.  This is a problem with google docs in general.  I believe that the workaround I've seen mentioned of putting the figure and caption into a table that is one column and two rows does not work either, but I have yet to experiment with that.  (And the caption would not wrap text either.)

Is there a workaround for this? 
Is this a feature you might be able to program in the future, if not here than in a seperate add on?

Thanks again, great work.

**Comment by johngallo** [comment]
Looks like there is another workaround, using Drawing, but it is klunky and will likely result in various font sizes for Labels throoughout the doc.
https://www.youtube.com/watch?v=AjmwJjMt9Y4

**Comment by davidrthorn** [comment]
As you say, I think this is one of those issues with Google Docs that are hard to fix with the limited control afforded to add-ons.

Tables would help, but I suspect would lead to (many) other formatting headaches.

This is definitely undesirable behaviour, though. It's not a bad idea to simply make another add on for pinning captions to images using tables and let users decide if they want to combine this with Cross Reference. I'll have a go at it at some point soon, time permitting.

Thanks for the feedback. Hopefully there's something that can be done in future.

**Comment by davidrthorn** [comment]
I think this can be avoided by making sure figure and caption are in the same paragraph and separated only by a line break (create with Shift+Enter). This way, Docs prefers not to split them up.

**Comment by johngallo** [comment]
@davidrthorn Great!
I was doing something similar by keeping the text on the same line as the figure, and then making the figure the width of the page.  But your way is better and allows the user to have the figure any size.   From what I gather at least. Thanks!

Will you add this to the wiki? https://github.com/davidrthorn/cross_reference/wiki/Cross-Reference-for-Google-Docs

Also, it takes a lot of clicks and concentration to find the wiki.  How about adding it as a link in the menu, or at least as #4 of getting started.  Something like:

"Getting started
1. Highlight reference in text→Ctrl+K→add link url as #fig_NAME (you choose name). 2. Highlight label →Ctrl+K→ add #figur_NAME (same name as before). 3. Go to 'Add-ons→Cross Reference→Update document' to apply. For tables, use #tab_NAME and #table_NAME. 4. Go to the wiki for more support: https://github.com/davidrthorn/cross_reference/wiki/Cross-Reference-for-Google-Docs "

**Comment by davidrthorn** [comment]
@johngallo yes, I need to get the docs up to scratch anyway, add some photos, maybe a video tutorial. Thanks for the feedback.

**Comment by johngallo** [comment]
I like how easy it is to find the wiki. Nice fix.  Thanks again David.
