### ISSUE TITLE
Improved instructions inc. photo/video

### ISSUE THREAD

**Issue by davidrthorn** [davidrthorn/cross_reference#19]
The instructions on using the add-on need to be drastically improved. Photos would help; a video tutorial would help even more.

**Comment by Deleetdk** [comment]
This is still needed. Case in point, I can't figure out how it works at all. How does one insert the caption text/mark image for counting? Instructions are unclear.

**Comment by nick-youngblut** [comment]
I agree that the instructions in the readme are very confusing
