### ISSUE TITLE
Jumping to figure/table/fnote does't work

### ISSUE THREAD

**Issue by hkennyv** [davidrthorn/cross_reference#21]
Hello,

I integrated this add-on into a google doc of mine. While all the figures/tables/fnotes translated and labeled correctly, clicking on the reference does not jump the section of the label. 

When clicking on the reference, I can see the URL change to "/edit#fno_yournamehere" however the page does not move. Similarly, the URL changes to "/edit#fnote_yournamehere" if I click on the label. 

I did not see any documentation in the README or wiki regarding this. Thank you!

**Comment by davidrthorn** [comment]
Hi Kenny

Jumping to labels is not currently a feature of Cross Reference. This is possible with Docs' native bookmarking feature.

See #20
