### ISSUE TITLE
List of Tables?

### ISSUE THREAD

**Issue by CaptainMurasa** [davidrthorn/cross_reference#22]
Does the List of Figures differentiate between the tables and figures list currently? If not, I would like to make an educated guess that it would be very similar to the List of Figures code where figures tag is replaced with the tables tag.

Love the app so far. Thanks for your contribution.

**Comment by Sendeman** [comment]
a label manager much like paperpile would be terriffic! Right now I use a notepad tab to keep track of all my labels.

**Comment by davidrthorn** [comment]
I'm back on this project and will look into creating list of tables soon

**Comment by davidrthorn** [comment]
List of tables is now released

**Comment by RFRIEDM** [comment]
The documentation doesn't currently with how to use it. 
"Cross Reference can create a list of figures akin to Docs' own table of contents. This feature is found under Add-ons→Cross Reference→List of figures. It inserts the list at the cursor or updates the existing list."
I don't have the option "List of figures", only configuration, so no list of figures or tables is inserted. Any tips?

**Comment by marbosjo** [comment]
I am facing the same issue as RFRIEDM, I do not see the option "List of figures":

![image](https://user-images.githubusercontent.com/5518122/114907113-062f4980-9e1b-11eb-801a-024a7e3da9b9.png)
