### ISSUE TITLE
Could we have a page number in the reference?

### ISSUE THREAD

**Issue by markNZed** [davidrthorn/cross_reference#28]
If a page number could be generated then it would allow more general references from one part of the text to another e.g. "see page 3". Great work on this add-on, thanks!

**Comment by davidrthorn** [comment]
Page numbers are very tricky in Google script because pages are not an element as far as the code is concerned. Pages are determined when a document is rendered for viewing; scripts only have access to the document as a collection of paragraphs, tables etc.

I hope this makes sense!

**Comment by markNZed** [comment]
Yes that makes sense. I see an issue raised for this in the App Script API. MS Word has the concept of a page cross-reference, something similar in Google Doc would be nice. If we had a user script that updated a table in the document mapping links to pages, would you extend your App Script to use this?

**Comment by markNZed** [comment]
Are you familiar with user scripts ? For example scripts installed via Tampermonkey in the Google Chrome browser.
