### ISSUE TITLE
Adding a suffix to references and labels

### ISSUE THREAD

**Issue by satary** [davidrthorn/cross_reference#29]
Hello? thanks for the great app!
One minor inconvenience is the inability to add suffixes. For example in Russian formal documentation equation numbers should be written in round brackets which is impossible right now. It may also be convenient to add dots and commas via suffixes.

**Comment by davidrthorn** [comment]
Hi satary

Thanks for the suggestion. This is a (relatively) simple feature. I'll take a look soon

**Comment by vadimreutskiy** [comment]
First, thank you for such a brilliant tool, which saves so much time on reviewing long documents and check for reference correspondence.

If you don't mind, can I ask the current status of this request?

**Comment by lime86** [comment]
Just started using the app, would also be very interested in this feature.

**Comment by davidrthorn** [comment]
Thanks all for your patience. I had to leave this project aside for a long time due to workload, but I'm now picking it up again.

I'll take look into implementing this soon.

**Comment by davidrthorn** [comment]
Solved in V2
