### ISSUE TITLE
More labels in the same paragraph

### ISSUE THREAD

**Issue by raveancic** [davidrthorn/cross_reference#30]
Hi David,
Thank you for sharing your app! it is great!

Unfortunately I am not able to insert more cross-ref in the same paragraph, is that normal?

If in my article I would like to write: "This investigation (Figure S1, Figure S2) brings me to the conclusion bla..bla..bla" I cannot insert for Figure S1 the hyperlink #fsupp_tree and for Figure S2 #fsupp_barplot coz it is telling me 
"Paragraphs may contain multiple references, but only one label. You probably meant to insert a reference. The last label in the paragraph has been highlighted in red." 

I would like to insert more label in the same paragraph tough,
Is it possible?

Thank you again
Ale

**Comment by davidrthorn** [comment]
Hi ale

I think you are talking about references. The example you give *refers* to two figures, but does not *label* them. @satary's comment above is accurate.

**Comment by raveancic** [comment]
Thank you for the replay @satary and @davidrthorn ,

So, basically I should prepare all the labels in order of appearance at the beginning of the file 
(figur_xx
figur_xy)
and then call them along the text as reference (fig_xx and fig_xy)...

My problem is that since I have a lot of supplementary figures (they actually do not appear as "figure/image" between paragraph) I name them for the first time even in the same paragraph, therefore I would insert them as labels and not as references. 

Thank  you in any case,

Ale
