### ISSUE TITLE
Custom labels not working

### ISSUE THREAD

**Issue by jordisunday** [davidrthorn/cross_reference#31]
Hi,
Great add-on, thank you for sharing it.
However, I can't use it with custom labels. "Figure #" doesn't work for me because my documents are not in English, so I tried to create new labels (5 letters long, of course) at the sidebar and I even tried to save them as defaults. It seems to work fine but when I try to use them I keep getting this message:

> The label starting #ima was not recognised.
> It might be a typo or it might be a custom label you
> have not yet added in the configuration sidebar.

Then, when I update the document I can only see the default "Figure #" label, so new labels are not correctly saved, assuming I'm not doing anything wrong.

Could it have to do with the fact I have logged in different Google accounts at the same time?

Thank you!

**Comment by davidrthorn** [comment]
if this still occurs please reopen
