### ISSUE TITLE
reference highlighted in red has nothing to refer to

### ISSUE THREAD

**Issue by nick-youngblut** [davidrthorn/cross_reference#40]
I created a custom cross reference for supplemental figures as described [here](https://lcolladotor.github.io/2019/04/02/how-to-write-academic-documents-with-googledocs/#.Xhdw3RdKhp8), but I just get the following when trying to use this custom cross reference:

```
The reference highlighted in red has nothing to refer to.
It might contain a typo or the corresponding label might be missing.

Updating the document when this has been fixed will automatically
restore the correct colour.
```

**Comment by davidrthorn** [comment]
Have you tried following the updated instructions in the readme?

**Comment by nick-youngblut** [comment]
Thank you for updating the docs! That helps out a lot.
