### ISSUE TITLE
Custom font size

### ISSUE THREAD

**Issue by davidrthorn** [davidrthorn/cross_reference#42]
Hi David,
I'm struggling a lot with font sizes. It's unclear how to control those for different reference types, and it turns finishing a project into a real pain in the butt.
Are there any updates regarding this issue?

Thanks a lot for your work!
Nic

_Originally posted by @karchern in https://github.com/davidrthorn/cross_reference/issues/25#issuecomment-544584819_

**Comment by wmayner** [comment]
Thanks for your great work on this extension!

The font size should probably be inferred from the surrounding text, i.e., not changed when the document is updated, if possible. I'm not sure if the way this is implemented would allow that. If not, then it would be great to have font size as a formatting option in the configuration panel.

**Comment by davidrthorn** [comment]
The ideal implementation would set font size to null unless the user has explicitly chosen to override it. This _should_ default to the size associated with the text style (e.g. normal, heading).

It might cause issues if the user has manually set the font size.

**Comment by davidrthorn** [comment]
Resolved in V2. Replacements are no longer resized.
