### ISSUE TITLE
Footnote numbering problem

### ISSUE THREAD

**Issue by yecko111** [davidrthorn/cross_reference#43]
When I start to create my second footnote, no matter what it is called (highlighting dummy words and create the hyperlink with code), e.g. #fnote_b or #fnote_second, it fails with error message named: "TypeError: details is not iterable"
However, my first footnote with hyperlink code #fnote_a and with reference #fno_a both work with no probelm
May I ask what happened and how can it be solved?
thank you in advanced

**Comment by davidrthorn** [comment]
Hi @yecko111, thanks for the feedback. Would you be happy to share this document with me or, if not, maybe share another document that reproduces the same problem? (email: davidrowthorn_at_gmail)

**Comment by yecko111** [comment]
https://docs.google.com/document/d/1MQYZaFEVtQm2n8acdNEk6vrDqDiFNekrgb_mXcIF8lY/edit
Here is the image from my screen when I would like to footnote the (b) part
https://imgur.com/a/HWrAPnQ#cTfEfaW

Thanks

**Comment by davidrthorn** [comment]
This was a confusion between labels and references.
