### ISSUE TITLE
Unable to Access settings

### ISSUE THREAD

**Issue by mrkensan** [davidrthorn/cross_reference#45]
I recently installed the plug-in, and am using it successfully, with the exception that I seem not to be able to view or modify any settings. Using the scroll buttons I am **unable** to see the settings. I have the plug in installed only for an account which was NOT the account that the Chrome Browser is logged in as. 

I then installed the plug in also for the account which the browser was logged as, I was able to see the list of applicable tags and their settings.

When the plug-in is uninstalled, once again, unable to see any of the settings. 

The plug-in continues to work doing replacements in docs associated with the account for which it was installed. So, besides not seeing or being able to modify the settings, the rest of the code seems to work as expected.

There might be a permissions/account settings issue to look at. One may not always want to grant permissions to their primary account, but only to say, a work account. I suspect the settings are being saved using the "browser" account and not into a space accessible by the account to which permissions were granted. When those are the same, no problem, things work as expected.

Thanks, and feel free to ask more questions if/when you get to looking into this. This problem is easily reproducible by in stalling as an account other than the one the browser is logged in as. When the plug-in is ALSO installed for an account matching the Browser account this works, if the plug-in is then uninstalled for the account matching the browser account, the settings no longer are listed/visible.

 Thanks for writing the plug-in, it's just perfect and something I've been waiting for since G-docs was created.

**Comment by davidrthorn** [comment]
Version 2 includes a major refactor which might solve this

**Comment by nbertenshaw** [comment]
I have the exact same issue. Is it likely to be resolved? I love the Add-on, but this is a bit of an inconvenience if I am on a different computer.
