### ISSUE TITLE
Add non-breaking space option (U+00A0, NO-BREAK SPACE)

### ISSUE THREAD

**Issue by jaguardo** [davidrthorn/cross_reference#47]
Great add-on, we have used it for awhile and love it!
Was curios if it is easy enough to change the "space" used in it (usually between the Equation, Figure, etc and the number) to a non-breaking space? So the label doesn't split over the end of the line?

Google Docs allows the special character, (U+00A0, NO-BREAK SPACE) to be used, so it might be a simple change.
Thanks!

**Comment by davidrthorn** [comment]
Thanks for the feedback jaguardo. Using a nbsp definately makes sense. I
can't think of any time that someone would want a breaking space there.

I'm in the process of a significant refactor. When that's done I'll look
into adding this feature.

>

**Comment by davidrthorn** [comment]
Fixed in V2
