### ISSUE TITLE
possible bug: possibly with nbsp, or multiple refs in a row.

### ISSUE THREAD

**Issue by johngallo** [davidrthorn/cross_reference#48]
Hello David,

Fantastic Add on!  I love it and have been using it for years.

First time ever I've hit a bug: it is with Figure 12 of this doc: https://docs.google.com/document/d/1Hsad2v3xXqyoPO-3eQBEKJD7GOhD_DLYdCrFaNqCGf0/edit# 

If you want to try to make edits, just ask for edit permissions, and in the meantime you can make suggestions and then note here that they have beenmade.

When I run the "Update Doc" 

I get:

"One of your paragraphs contains more than one label.

Paragraphs may contain multiple references, but only one label.
You probably meant to insert a reference. The last label in
the paragraph has been highlighed in red."

But that is not what is happening as far as I can tel. I've even tried new lable names, redoing it inthe paragraph above, etc.

Any suggestions?

Thanks,

John

**Comment by johngallo** [comment]
looks like I am going to have to label all the figures the old fashioned way... sigh.

**Comment by davidrthorn** [comment]
Hi John, sorry for the late reply. Can you give me edit permission (davidrowthorn@gmail.com)?

**Comment by johngallo** [comment]
Thanks David!  OK you should have edit permissions now.  And, this is a
forked version of the doc, not the actual one now.  So feel free to make
major changes/tests

John Gallo, Ph.D.
Senior Scientist
Conservation Biology Institute <https://consbio.org/people/staff/john-gallo>
136 SW Washington Avenue, Suite 202
Corvallis, OR 97333
Remote Office: Inglenook, CA
Phone: 707.962.9078
Twitter: @johnagallo <https://twitter.com/johnagallo>
Updates: Action Research Newsletter
<https://consbio.us9.list-manage.com/subscribe?u=3dea159e4cbe0a0ff3b43eadd&id=e3bd82fd81>

**Comment by davidrthorn** [comment]
I've had a play with the document and it look like a straight up bug to me. I'm on the verge of releasing a significant overhaul, so I'm going to put my efforts into that and hope that it resolves this issue, since there has been some change in how errors are handled.

**Comment by johngallo** [comment]
ok, thanks for taking a look. I fixed things manually and will publish. Great to hear about the continued development. Thanks so much!
