### ISSUE TITLE
I cant change the label

### ISSUE THREAD

**Issue by Madied94** [davidrthorn/cross_reference#49]
Hi, im having troubles with Cross Reference, i cant change de custom's labels, so, its there any solution for this problem?

**Comment by davidrthorn** [comment]
Can you be a little more specific about what you're trying to do, what you expect to happen and what actually happens? Thanks

**Comment by venabled** [comment]
I've been having an issue recently (last few months) where the `Configure References` menu brings up the side panel but is grayed out with a status/loading indicator in the middle.

![image](https://user-images.githubusercontent.com/1444624/107429571-1280e880-6af2-11eb-850b-7beeb56d003a.png)

**Comment by davidrthorn** [comment]
@venabled have you tried fresh install?

If so, could you try opening the sidebar with the [developer console](https://balsamiq.com/support/faqs/browserconsole/) open and paste the result?

**Comment by Luan1** [comment]
I have the same problem

![erro label](https://user-images.githubusercontent.com/5663911/107649513-4b3cd100-6c5c-11eb-97ba-b998c4705c73.png)

**Comment by Luan1** [comment]
OBS: My doc have 250 images.

**Comment by venabled** [comment]
I don't think we're running a recent install, Ill ask our admin to uninstall/reinstall and report back.

Thanks for the suggestion, sorry for the churn here.

**Comment by venabled** [comment]
![image](https://user-images.githubusercontent.com/1444624/107654553-bed8e100-6c50-11eb-993c-21ffcc3803de.png)

**Comment by davidrthorn** [comment]
Thanks @venabled. Would you be willing to share your document (or an example document with the same problem) via a private message? It would be easier for me to diagnose the issue that way.

**Comment by davidrthorn** [comment]
This turned out to be that the network was blocking external js

**Comment by lucia-ramirez** [comment]
Hello, I am having the same issue as @venabled. How did you resolve it?
