### ISSUE TITLE
Cross referencing direct to embedded drawings/images

### ISSUE THREAD

**Issue by jrmxn** [davidrthorn/cross_reference#51]
I have the following difficulty:

I usually insert figures in google docs with tables: figure in top row, and caption in second row with cross reference.

However, I am currently having to collaborate on a document where text has to flow around my figures. A limitation of google docs is that you can't make text flow around tables though.

The workaround is to put figure and text into a google drawing and then embed that (and here is why I am posting this here):
I then can't use cross reference because even though I attach a #figur link to the embedded drawing (i.e. with ctrl+k or in alt-text title) cross reference doesn't pick it up (not unexpectedly).

I am wondering if a feature to get cross-reference to look into the figure link or alt-text could be added...

Thanks - 

EDIT: I realize you wouldn't be able to display "Figure 1" in the actual figure, but at least all references to that figure would change consistently if the figure gets moved about.

**Comment by davidrthorn** [comment]
The add on works by iterating through paragraphs within a document. I don't think Google offers any way to include drawings in this process, so this would not be possible.

If more people reported a need for such a feature I'd consider researching a workaround, but it sounds like a fairly niche use case to me.

**Comment by jrmxn** [comment]
Alright. thanks for giving it some thought. Definitely niche - if only google would just allow text wrapping on tables.
