### ISSUE TITLE
References are numbered in reverse order

### ISSUE THREAD

**Issue by juanchossn** [davidrthorn/cross_reference#52]
Hi!
I've been trying to use the Cross Reference add on, and the figure numbers are created reversely! Is there a way a can modify this?

Thanks, Juan

![Screenshot from 2020-09-15 16-49-31](https://user-images.githubusercontent.com/42919682/93257610-7f769900-f773-11ea-813a-913cba70da0f.png)

**Comment by davidrthorn** [comment]
Would you mind sharing the document with me so I could take a look?

**Comment by juanchossn** [comment]
Hi!

I closed it and opened it again and it works fine now =). It seems to be a bug of the first usage (?)

![Screenshot from 2020-09-15 16-57-03](https://user-images.githubusercontent.com/42919682/93258405-9f5a8c80-f774-11ea-88d9-6460d8dbc873.png)

Regards, Juan

**Comment by davidrthorn** [comment]
Glad it's working for you now!
