### ISSUE TITLE
Broken Link of Privacy Policy

### ISSUE THREAD

**Issue by yasirroni** [davidrthorn/cross_reference#55]
**BUG**
from `https://accounts.google.com/signin/oauth/consent?authuser...`, there is a link to Privacy Policy to `http://davidrowthorn.net/cr-privacy-policy.html`. Unfortunately, this link returns 404 HTML error.

**EXPECTED BEHAVIOUR**
Show `http://davidrowthorn.net/gdocs/cross_reference/privacy.html`

**HOW TO REPRODUCE**
1. Open `https://gsuite.google.com/marketplace/app/cross_reference/269114033347`
2. Install
3. Continue
4. Privacy Policy

**Comment by davidrthorn** [comment]
Updated
