### ISSUE TITLE
Can't search for figure text with Ctrl-F

### ISSUE THREAD

**Issue by insane-dreamer** [davidrthorn/cross_reference#58]
Thanks for the awesome plugin. What a time saver! One little thing is after running Update Document it seems that it's not possible to search (Ctrl-F) for the replaced text (i.e., "Figure 2" or whatever string was originally used). (Once exported to PDF, this text does become searchable, but if you're working on a document in gDoc and need to find the figure with Find, that doesn't seem possible). Is there any workaround? Thanks.

**Comment by davidrthorn** [comment]
Just to I understand, are you saying a) that it is not possible to find figures by their label (e.g. `#figur_somename`) or b) it is not possible to find them by searching for the text that was replaced when updating (this could be anything)? So in (b), you write `blah` and then you add a label to it and the app replaces `blah` with `Figure 1`.

**Comment by insane-dreamer** [comment]
Sorry that was unclear. The case is b). Once the replacement has been made, the new figure labels are not searchable.

**Comment by davidrthorn** [comment]
This has to do with the way that Google Docs searches I think. It doesn't search hyperlinks, and labels are just hyperlinks. It's not something I can control unfortunately.

It's a fairly popular request to have some form of visual label management, so I'll probably put some thought into that. At least then you could see your labels listed and click them to go to then in the document.
