### ISSUE TITLE
Figure list without page number and link with click

### ISSUE THREAD

**Issue by Luan1** [davidrthorn/cross_reference#59]
Hi team! 

Congratulations on the work. My document has 250 images and does not generate the list with the page numbers, would it be possible to generate the list without the numbers? And does the list have the same functionality as the summary? In which you click and go straight to the image

**Comment by davidrthorn** [comment]
Without looking at the document it's hard to say for sure what's causing page numbers to fail. It could just be the number of figures. The add on uses a rather dirty hack to number pages (thanks to Google Docs' very limited API in this area), so very long documents can timeout.

It is not possible currently to generate lists of figures without numbers. I can't see a compelling use case for this, but I'm open to feedback.

The list of figures does not link to the figures. Google Docs' API again makes this kind of thing difficult, although not impossible. I might consider it as a feature if there's enough demand.
