### ISSUE TITLE
Custom names not working

### ISSUE THREAD

**Issue by feidaman** [davidrthorn/cross_reference#6]
Hi, just installed Cross Reference. I'm trying to define custom names to use in adidion to the stock figure, table and equation ones, but the **Save and Apply** button is always disabled, am I doing something wrong? Thanks!

**Comment by davidrthorn** [comment]
Hi Feidaman. I can't recreate this, but perhaps others can. The save button is disabled unless the chosen label code is 5 letters long. Is that the length your using?

**Comment by feidaman** [comment]
Oops! That did it. I think I must have misread that as "label length cannot exceed 5 characters". This is working as expected, thanks!
