### ISSUE TITLE
Some issues with customization and lists

### ISSUE THREAD

**Issue by Robin-Venhuizen** [davidrthorn/cross_reference#61]
Hi there,
I'm using this add-on as a way to organise figures for my thesis and it works great for that!
However, just like venabled in another thread, I can't customize my labels or my lists. It gets stuck on the loading screen.
Another issue I'm having is with lists. 
Whenever I insert a list it only inserts the figure names followed by ... (no page numbers). Am I not waiting long enough or is something wrong? I had it running for about 10 minutes and since my document is 14 pages long with only 7 figures I figured that would be enough.

If you need it here is the console output when trying to configure lists
![image](https://user-images.githubusercontent.com/49907540/112620631-1611ca00-8e29-11eb-89f0-e6ebd1c97dcd.png)

Hope this can be solved :)

**Comment by davidrthorn** [comment]
You definitely shouldn't wait that long for lists of figures. Could you try the following:

1. Disable AdBlocker
2. - Uninstall add on
3. - Reinstall add on

**Comment by Robin-Venhuizen** [comment]
Thanks for responding so quickly!
However, sadly that didn't seem to work. got any other ideas?
Configuring also still does not work.

**Comment by davidrthorn** [comment]
@Robin-Venhuizen the easiest thing to do is for me to access the document if you're willing to share (davidrowthorn@gmail.com). That way I can try to reproduce the issue and investigate. Otherwise, if you want to make a dummy document with the same problem (assuming this happens in all your documents), I could access that?

**Comment by Robin-Venhuizen** [comment]
i created a dummy document and added you to it :)

**Comment by davidrthorn** [comment]
Thanksn@Robin-Venhuizen. I'm able to customise labels and references in the document you shared with me. Can you confirm that you are still not able to open the customisation panel?

I'm not able to generate a list of figures even when I copy your document to my local docs, which is odd. I can't see any console errors either. All I can think at this point is that some kind of permission issue is blocking the use of the third-party PDF library used to generate lists.

This would explain why you also can't open the sidebar, which uses an external js library. 

Is your Google Docs account administrated by an organisation or is it personal?

At this point it would be helpful for you to try:

1. Reproducing the problem in Incognito Mode in Chrome (or disabling all extensions)
2. Reproducing the problem in your personal google docs account (if  you're using a centrally managed one and you have a personal one)
3. Trying  a different browser.

**Comment by Robin-Venhuizen** [comment]
Hey David,
It seems that my university has blocked the use of third-party PDF libraries like you said, as the add-on works perfectly on my personal account.
I'll try to get in contact with them and hope for the best :)
Thanks again it is really appreciated
