### ISSUE TITLE
Click on the reference link does not take to the hyperlinked page

### ISSUE THREAD

**Issue by DrNguyen2525** [davidrthorn/cross_reference#66]
Hi, thanks for your great work on this Add-On.

However, it does not work for me now. When I click on the reference link, it does not take me to the hyperlinked page.
I have followed exactly the instructions you provided in the docs. I have created a label as `#figur_1` and a reference link as `#fig_1`. But nothing happens when I click on the `#fig_1` reference link.

What am I doing wrong?

**Comment by davidrthorn** [comment]
The add on does not provide clickable links for references. It numbers
references according to which figure that refer to

**Comment by DrNguyen2525** [comment]
@davidrthorn Okay I got it. But do you consider building the clickable reference links feature as I mentioned above?

**Comment by davidrthorn** [comment]
Probably not right now to be honest because I can't think of a good way to
do it given the limited Google Docs API
