### ISSUE TITLE
Update function not available

### ISSUE THREAD

**Issue by JessicaRudi** [davidrthorn/cross_reference#68]
Hi,

my Admin just installed cross reference and I created my first label and reference but I cannot update the document. 
'Add-ons->cross reference' only shows "help" but nothing else. There is one similar issue here but it is closed without any expalantion.
What do I nee to do?

**Comment by davidrthorn** [comment]
This is almost certainly a permissions issue to do with what your admin
allows rather than an issue with the add on. I would ask them if they can
review your permissions regarding add ons
