### ISSUE TITLE
Cannot delete stock names

### ISSUE THREAD

**Issue by feidaman** [davidrthorn/cross_reference#7]
I am trying to delete the stock names to replace them with my own, shorter ones. Instead of **#figur** and **#fig**, I would like to use just **#_fig** and **#fig**, as I find these easier to distinguish. However, if I delete the **Figure** entry, it always comes back even after I click **Save and apply**. Furthermore, the Equation entry does not provide a **Delete** button, which seems odd (although not so odd considering deleting Figure and Table doesn't seem to work anyway).

Ideally what I woulld like to do is be able to edit existing entries' **Code** fields, but I suppose this may not propagate well to documents that contain labels and references establish prior to editing the codes.

Thanks!

**Comment by davidrthorn** [comment]
Thanks for pointing out the delete bug inadvertently! You should never have been given the option to delete the figure entry. As for your actual request, at the moment the stock names (figure, equation, table) are locked. This might change in future, but at the moment it makes the code simpler and therefore less error-prone. Unfortunately, your desired prefix "_fig" is not long enough. Cross Reference requires 5 letter label codes. Again, this might change in future.

**Comment by feidaman** [comment]
Now I understand. The reference code is basically the label code minus the last two characters. Turning this around, I suppose I could use "fig__" (note: two underscores) and "fig" to the same effect, but this isn't possible at the moment because the "fig" is already taken by the stock names which can't be edited.

This is going to seem extremely picky, but the idea was that using two underscores saves a tiny amount of brain power by having to remember 3- instead of 5-character codes. Users would mentally associate the "__" part with "label", and absence of "__" with "reference".

Anyway, I haven't used your add-on enough yet, so it's very possible I might get used to how it works at the moment. It is a very handy add-on anyway. I've only started using Google Docs a week ago (mostly for its collaborative features) and, while I don't expect it to be a full-fledged word processor like MS Word, I was a bit surprised it couldn't do cross-referencing natively.
